# Generated by Django 5.0.9 on 2024-11-28 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_access',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_owner',
        ),
        migrations.AddField(
            model_name='note',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='notes_accessible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('text', 'Text')], max_length=10),
        ),
    ]
